-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    users_id bigserial NOT NULL,
    users_email character varying,
    users_phone character varying(15),
    users_password character varying(255) NOT NULL,
    users_creation_date date NOT NULL,
    users_login_key character varying,
    CONSTRAINT id PRIMARY KEY (users_id),
    CONSTRAINT email UNIQUE (users_email),
    CONSTRAINT phone UNIQUE (users_phone)
);

CREATE TABLE IF NOT EXISTS public.profiles
(
    users_id bigint NOT NULL,
    profile_username character varying(31) NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    birth_date date,
    profile_biography text,
    profile_image character varying,
    profile_gender character varying,
    PRIMARY KEY (profile_username)
);

ALTER TABLE IF EXISTS public.profiles
    ADD CONSTRAINT users_id FOREIGN KEY (users_id)
    REFERENCES public.users (users_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;